/**
 * Autogenerated by Thrift Compiler (0.9.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "TextToVoice_constants.h"

namespace ThriftServer {

const TextToVoiceConstants g_TextToVoice_constants;

TextToVoiceConstants::TextToVoiceConstants() {
}

} // namespace

