/**
 * Autogenerated by Thrift Compiler (0.9.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef TextToVoice_CONSTANTS_H
#define TextToVoice_CONSTANTS_H

#include "TextToVoice_types.h"

namespace ThriftServer {

class TextToVoiceConstants {
 public:
  TextToVoiceConstants();

};

extern const TextToVoiceConstants g_TextToVoice_constants;

} // namespace

#endif
