/**
 * Autogenerated by Thrift Compiler (0.9.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "VoiceToText_constants.h"

namespace ThriftServer {

const VoiceToTextConstants g_VoiceToText_constants;

VoiceToTextConstants::VoiceToTextConstants() {
}

} // namespace

