/**
 * Autogenerated by Thrift Compiler (0.9.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef VoiceToText_CONSTANTS_H
#define VoiceToText_CONSTANTS_H

#include "VoiceToText_types.h"

namespace ThriftServer {

class VoiceToTextConstants {
 public:
  VoiceToTextConstants();

};

extern const VoiceToTextConstants g_VoiceToText_constants;

} // namespace

#endif
